Update phpcs.yml

diff --git a/.github/workflows/phpcs.yml b/.github/workflows/phpcs.yml
--- a/.github/workflows/phpcs.yml
+++ b/.github/workflows/phpcs.yml
@@ -35,12 +35,14 @@ jobs:
 
       # Install dependencies
       - name: Install dependencies
-        run: composer install --no-progress
+        run: composer install --no-progress --prefer-dist
 
-      # Fix code using PHPCBF
+      # Check if PHPCBF fixes all issues
       - name: Run PHP Code Beautifier and Fixer (PHPCBF)
-        run: vendor/bin/phpcbf --standard=PSR12 src/
+        run: |
+          vendor/bin/phpcbf --standard=PSR12 src/
+          vendor/bin/phpcs --standard=PSR12 src/ || true
 
-      # Verify with PHP Code Sniffer
-      - name: Run PHP Code Sniffer
+      # Fail if PHPCS finds errors
+      - name: Verify with PHP Code Sniffer
         run: vendor/bin/phpcs --standard=PSR12 src/
